# Generated by Django 3.1.4 on 2021-01-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('stduent_ID', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
